using System;
using System.Collections.Generic;
using System.Text;
using X.Data.Attributes;

namespace X.Data.Entitys
{
    [AutoGeneratedController]
    public  class PurchasingOrder:EntityBase
    {
         

    }
}
