using System;
using System.Collections.Generic;
using System.Text;
using Data.Attributes;

namespace Data.Entitys
{
    [AutoGeneratedController]
    public  class PurchasingOrder:EntityBase
    {
         

    }
}
