
using Data.Entitys;
using Microsoft.AspNet.OData.Builder;
using Microsoft.OData.Edm;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.OData.Routing.Conventions;
using Microsoft.AspNetCore.Mvc.Controllers;
using Microsoft.AspNetCore.Routing;
using Microsoft.AspNet.OData.Routing;
using System.Reflection;
using Microsoft.AspNetCore.Mvc;
using Data.Attributes;

namespace WebService.Api
{
    public static class ODataConfig
    {
        public static IEdmModel GetEdmModel()
        {
            ODataConventionModelBuilder builder = new ODataConventionModelBuilder();
            var types = typeof(EntityBase).Assembly.GetTypes();
            foreach (var type in types)
            {
                if (type.BaseType == typeof(EntityBase) && type.GetCustomAttribute<AutoGeneratedOdataControllerAttribute>() is AutoGeneratedOdataControllerAttribute)
                {
                    builder.AddEntitySet(type.Name, builder.AddEntityType(type));      
                }
            }
           
            return builder.GetEdmModel();
        }
    }
}
